myproject/books/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # /books/
    path('', views.index.as_view(), name='index'),
    # /books/id
    path('register/',views.UserFormView.as_view(),name='username'),
    # registration
    path('<pk>/', views.details.as_view(), name='details')
   
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('books/',include('books.urls')),
    path('admin/', admin.site.urls)
]

myproject/books/models.py
from django.db import models


class Collection(models.Model):
    book_name=models.CharField(max_length=100)
    discription=models.CharField(max_length=500)
    bookcover=models.CharField(max_length=1000)
    def __str__(selfe) :
        return selfe.book_name
    
class piece(models.Model):
    collection=models.ForeignKey(Collection,on_delete=models.CASCADE)
    title=models.CharField(max_length=200)
    type=models.CharField(max_length=200)
    artist=models.CharField(max_length=200)
    year=models.IntegerField()
    piececover=models.CharField(max_length=1000)
    def __str__(selfe) :
        return selfe.title
# Create your models here.

myproject/books/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

myproject/books/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Collection, piece
from django.views import generic
from.forms import UserForm
from django.contrib.auth import authenticate,login
from django.views.generic import View


class index(generic.ListView):
    template_name='books/bookstemp.html'
    def get_queryset(self):
        return Collection.objects.all()

class details(generic.DetailView):
    model=Collection
    template_name="books/detailstemp.html"

class UserFormView(View):
    form_class=UserForm
    template_name="books/formtemp.html"

    def get(self,request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})
    
    def post(self,request):
        form=self.form_class(request.POST)
        if form.is_valid():
            user=form.save()   #changed
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            newuser=authenticate(username=username,password=password)

            if newuser is not None:
                if newuser.is_active:
                    login(request,newuser)
                    return redirect("/books")
        return render(request,self.template_name,{'form':form})

myproject/books/templates/books/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>ase</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
     <div class="container-fluid">
       <div class="navbar-header">
        <a class="navbar-brand" href="/books">Home</a></a>
     </div>
    <ul class="nav navbar-nav navbar-right">
        <li class="">
            <a href="/books/register">Register</a>
        </li>
        <li class="">
            <a>{{request.user}}</a>
        </li>
    </ul>
</div>   
</nav>
{% block content %}  
{% endblock %}
</body>
</html>

myproject/books/templates/books/bookstemp.html
<!DOCTYPE html>
{% extends 'books/base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BooksStall</title>
</head>
<body>
  {% block content %}
  {%    for Booksobj in object_list     %}
  <div align="center">
            <img src="{{Booksobj.bookcover}}" height="200" width="200">
            <h2><a href="/books/{{Booksobj.id}}">{{Booksobj.book_name}}</a></h2>
            <h3>{{Booksobj.discription}}</h3>
            <br/>
   {% endfor %}
   {% endblock %}
</div>
</body>

</html>

myproject/books/templates/books/detailstemp.html
<!DOCTYPE html>
{% extends 'books/base.html' %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Piece</title>

    </head>
    <body>
        {% block content %}
        {% for pieceobj in object.piece_set.all    %}
        <div align="center">
               <img src="{{pieceobj.piececover}}" height="200" width="200">
               <h2>{{pieceobj.title}} - {{pieceobj.artist}}</h2>
               <h3>{{pieceobj.type}}</h3>
               <h3>{{pieceobj.year}}</h3>
               <br/>
            </div>
        {% endfor %}
        {% endblock %}
    </body>
</html>

myproject/books/templates/books/formtemp.html
<!DOCTYPE html>
{% extends 'books/base.html' %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Registration</title>

    </head>
    <body>
        {% block content %}
        <form action="" method="post">
            {% csrf_token %}
            User name:
            <input type="text" name="username">
            <br/><br/>

            Email:
            <input type="email" name="email">
            <br/><br/>

            Password:
            <input type="password" name="password">
            <br/>

            <input type="submit" value="submit">
        
        </form>
        {% endblock %}
    </body>
    </html>